In [13]:
#Import dependencies
import findspark
findspark.init()
import pyspark
from pyspark.sql import SparkSession
import pandas as pd
from pyspark import SparkFiles
spark = SparkSession.builder.appName("DataFrame Basics").getOrCreate()

In [6]:
#import data using spark
df= spark.read.format("csv").option('header','true').load("diabetes_prediction_dataset.csv")
df.show()

+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
|gender| age|hypertension|heart_disease|smoking_history|  bmi|HbA1c_level|blood_glucose_level|diabetes|
+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
|Female|80.0|           0|            1|          never|25.19|        6.6|                140|       0|
|Female|54.0|           0|            0|        No Info|27.32|        6.6|                 80|       0|
|  Male|28.0|           0|            0|          never|27.32|        5.7|                158|       0|
|Female|36.0|           0|            0|        current|23.45|        5.0|                155|       0|
|  Male|76.0|           1|            1|        current|20.14|        4.8|                155|       0|
|Female|20.0|           0|            0|          never|27.32|        6.6|                 85|       0|
|Female|44.0|           0|            0|          never|19.31|        6.5|                200|       1|
|Female|79.0|           0|            0|        No Info|23.86|        5.7|                 85|       0|
|  Male|42.0|           0|            0|          never|33.64|        4.8|                145|       0|
|Female|32.0|           0|            0|          never|27.32|        5.0|                100|       0|
|Female|53.0|           0|            0|          never|27.32|        6.1|                 85|       0|
|Female|54.0|           0|            0|         former| 54.7|        6.0|                100|       0|
|Female|78.0|           0|            0|         former|36.05|        5.0|                130|       0|
|Female|67.0|           0|            0|          never|25.69|        5.8|                200|       0|
|Female|76.0|           0|            0|        No Info|27.32|        5.0|                160|       0|
|  Male|78.0|           0|            0|        No Info|27.32|        6.6|                126|       0|
|  Male|15.0|           0|            0|          never|30.36|        6.1|                200|       0|
|Female|42.0|           0|            0|          never|24.48|        5.7|                158|       0|
|Female|42.0|           0|            0|        No Info|27.32|        5.7|                 80|       0|
|  Male|37.0|           0|            0|           ever|25.72|        3.5|                159|       0|
+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
only showing top 20 rows

In [9]:
#filter out 'ever' (mispelled) and 'No Info' (unecessary data) from the smoking_history columnn
df_filtered = df.where((df.smoking_history!='ever') & (df.smoking_history!='No Info'))
df_filtered.show()

+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
|gender| age|hypertension|heart_disease|smoking_history|  bmi|HbA1c_level|blood_glucose_level|diabetes|
+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
|Female|80.0|           0|            1|          never|25.19|        6.6|                140|       0|
|  Male|28.0|           0|            0|          never|27.32|        5.7|                158|       0|
|Female|36.0|           0|            0|        current|23.45|        5.0|                155|       0|
|  Male|76.0|           1|            1|        current|20.14|        4.8|                155|       0|
|Female|20.0|           0|            0|          never|27.32|        6.6|                 85|       0|
|Female|44.0|           0|            0|          never|19.31|        6.5|                200|       1|
|  Male|42.0|           0|            0|          never|33.64|        4.8|                145|       0|
|Female|32.0|           0|            0|          never|27.32|        5.0|                100|       0|
|Female|53.0|           0|            0|          never|27.32|        6.1|                 85|       0|
|Female|54.0|           0|            0|         former| 54.7|        6.0|                100|       0|
|Female|78.0|           0|            0|         former|36.05|        5.0|                130|       0|
|Female|67.0|           0|            0|          never|25.69|        5.8|                200|       0|
|  Male|15.0|           0|            0|          never|30.36|        6.1|                200|       0|
|Female|42.0|           0|            0|          never|24.48|        5.7|                158|       0|
|  Male|40.0|           0|            0|        current|36.38|        6.0|                 90|       0|
|Female|69.0|           0|            0|          never|21.24|        4.8|                 85|       0|
|Female|72.0|           0|            1|         former|27.94|        6.5|                130|       0|
|  Male|30.0|           0|            0|          never|33.76|        6.1|                126|       0|
|  Male|67.0|           0|            1|    not current|27.32|        6.5|                200|       1|
|  Male|40.0|           0|            0|         former|27.85|        5.8|                 80|       0|
+------+----+------------+-------------+---------------+-----+-----------+-------------------+--------+
only showing top 20 rows

In [15]:
#Confirm rows reduced 
Diabetes_Prediction_df = df_filtered.toPandas()
Diabetes_Prediction_df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Male,28.0,0,0,never,27.32,5.7,158,0
2,Female,36.0,0,0,current,23.45,5.0,155,0
3,Male,76.0,1,1,current,20.14,4.8,155,0
4,Female,20.0,0,0,never,27.32,6.6,85,0